name: Server Rules
version: '${project.version}'
main: mc.skykingpx.serverrules.ServerRules
api-version: '1.13'
commands:
  rules:
    description: Read the Server Rules.
    usage: /<command>
    permission: serverrules.rules